# Generated by Django 3.2.7 on 2021-10-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('JWT', 'JWT'), ('OAuth', 'OAuth')], max_length=50)),
            ],
        ),
    ]
